
# File: azure-pipelines.yml
trigger:
- master

variables:
  - group: quick-start-vg
  - name: SERVICE
    value: cleanup-export

stages:
  - stage: docker_cleanup_export
    dependsOn: build_test
    jobs:
    - job: build_push_cleanup_export
      pool:
        vmImage: 'Ubuntu 16.04'
      steps:
      - script: echo $(SERVICE)!
      - script: |
          # Login to Azure 
          echo "az login --service-principal --username $(SP_APP_ID) --password $(SP_PASS) --tenant $(SP_TENANT)"
          az login --service-principal --username "$(SP_APP_ID)" --password "$(SP_PASS)" --tenant "$(SP_TENANT)"
      displayName: 'Azure Login'